# Read the TLS certificate chain exposed by the EKS OIDC issuer.
data "tls_certificate" "eks_oidc" {
  # Create this lookup only when IRSA is enabled.
  count = var.enable_irsa ? 1 : 0

  # Use the issuer URL generated by the EKS control plane.
  url = aws_eks_cluster.main.identity[0].oidc[0].issuer
}

# Register the EKS OIDC issuer as an IAM identity provider.
resource "aws_iam_openid_connect_provider" "eks" {
  # Create the IAM OIDC provider only when IRSA is enabled.
  count = var.enable_irsa ? 1 : 0

  # Allow Kubernetes service accounts to request AWS STS credentials.
  client_id_list = ["sts.amazonaws.com"]

  # Trust the certificate fingerprint returned by the issuer endpoint.
  thumbprint_list = [
    data.tls_certificate.eks_oidc[0].certificates[0].sha1_fingerprint
  ]

  # Use the OIDC issuer URL generated for this EKS cluster.
  url = aws_eks_cluster.main.identity[0].oidc[0].issuer

  tags = merge(
    local.common_tags,
    {
      Name = "${local.name_prefix}-eks-oidc"
      Role = "eks-oidc-provider"
    }
  )
}

# Build the issuer host and path used in IAM trust-policy conditions.
locals {
  oidc_issuer_hostpath = replace(
    aws_eks_cluster.main.identity[0].oidc[0].issuer,
    "https://",
    ""
  )
}

# Create the trust policy for the aws-node service account.
data "aws_iam_policy_document" "vpc_cni_assume_role" {
  # Create the policy only when IRSA is enabled.
  count = var.enable_irsa ? 1 : 0

  statement {
    # Allow a Kubernetes service account token to assume this role.
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      # Trust the IAM OIDC provider created for this cluster.
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.eks[0].arn]
    }

    condition {
      # Require the expected STS audience.
      test     = "StringEquals"
      variable = "${local.oidc_issuer_hostpath}:aud"
      values   = ["sts.amazonaws.com"]
    }

    condition {
      # Restrict the role to only the aws-node service account.
      test     = "StringEquals"
      variable = "${local.oidc_issuer_hostpath}:sub"
      values   = ["system:serviceaccount:kube-system:aws-node"]
    }
  }
}

# Create a dedicated IAM role for the Amazon VPC CNI.
resource "aws_iam_role" "vpc_cni" {
  # Create the role only when IRSA is enabled.
  count = var.enable_irsa ? 1 : 0

  # Use a stable and readable role name.
  name = "${local.name_prefix}-vpc-cni-role"

  # Allow only the aws-node service account to assume this role.
  assume_role_policy = data.aws_iam_policy_document.vpc_cni_assume_role[0].json

  tags = merge(
    local.common_tags,
    {
      Name = "${local.name_prefix}-vpc-cni-role"
      Role = "vpc-cni"
    }
  )
}

# Grant the dedicated CNI role the AWS-managed VPC CNI permissions.
resource "aws_iam_role_policy_attachment" "vpc_cni_policy" {
  # Create this attachment only when IRSA is enabled.
  count = var.enable_irsa ? 1 : 0

  # Attach the policy to the dedicated CNI role.
  role = aws_iam_role.vpc_cni[0].name

  # Grant ENI and IP address management permissions.
  policy_arn = data.aws_iam_policy.eks_cni_policy.arn
}