name: Coupon Service CI

on:
  workflow_dispatch:


permissions:
  contents: read
  checks: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build and Test Coupon Service
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service-name: Coupon Service
      service-path: services/coupon-service
      docker-image-name: coupon-service
    #secrets: inherit