name: Pricing Service CI

on:
  workflow_dispatch:


permissions:
  contents: read
  checks: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build and Test Pricing Service
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service-name: Pricing Service
      service-path: services/pricing-service
      docker-image-name: pricing-service
    #secrets: inherit