name: Terraform - Live Alpha

on:
  workflow_dispatch:

concurrency:
  group: terraform-live-alpha-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment-name: alpha
      working-directory: platform/terraform/live/aws/alpha
      state-key: atlas-commerce/alpha/terraform.tfstate
      require-master: false
